# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0722750046ac215f7142e8f063a84ae8365f69d6062e9fd25e7ddf28897df2aa55a090fd73e42369473aea108531910d18da12cd27038ea9ba48378f60d358bd

test:
  secret_key_base: 7b88da009e8ae4e56b0741815be80330dd38f28d5e0b0405c8544c35a99b8cd00358ced823b293e8c442d224a72b5fc9e70b5957b11deae75678a882d6bbfd6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
